### ISSUE TITLE
syncing with attachments

### ISSUE THREAD

**Issue by smokeofc** [Magic-Bots/xenon#69]
After the last fix related to syncing with attachments, where it were only posting an empty box, it now has another problem:

![image](https://user-images.githubusercontent.com/13959015/65353175-c2e40900-dbec-11e9-9773-2a5216587acd.png)

My setup is as follows:
The main server is syncing all channels to a "backup server", it's also syncing a handful of channels to a "friends only" server. The channels that're synced to both of those servers experience what's in the screenshot above; it syncs properly to one of the servers, and with empty files to the second.

**Comment by merlinfuchs** [comment]
I didn't think about that. I need to put the cursor back to the beginning of the file.

**Comment by merlinfuchs** [comment]
should be fixed

**Comment by smokeofc** [comment]
No, still experience the same issue in the same circumstances.
tried to disable and re-enable, but same story

**Comment by merlinfuchs** [comment]
Please try again now. Keep in mind that big files (over 8 MB) might not work.

**Comment by merlinfuchs** [comment]
Please give me feedback on this ...

**Comment by smokeofc** [comment]
Sorry, got sick.
The problem seems resolved.

Thank you! 👍

**Comment by merlinfuchs** [comment]
👍 Get well soon!
